### ISSUE TITLE
Grey Screen

### ISSUE THREAD

**Issue by thesnowfury** [WowUp/WowUp.CF#63]
**Describe the bug**
After opening WoWup and clicking update on any addon that requires an update, the app becomes a grey rectangle and no update action is taken. Pressing reload or force reload brings back the initial addon listing/update screen but again, pressing any update button or update all reverts back to a big grey rectangle.

**To Reproduce**
1. Open wowup
2. Click on update or update all
3. Application is now grey rectangle

**Expected behavior**
Addons update

**Screenshots**
Attached

**Desktop (please complete the following information):**
 - OS: Garuda Linux
 - Browser Firedragon 
 - Version 117.0.1

**Additional context**

![Screenshot_20230914_091246](https://github.com/WowUp/WowUp.CF/assets/58730588/6bfe4263-1e59-4ec9-909f-16075e65fdd6)

**Comment by Kyra-Lee** [comment]
I am also having this behavior.  I am on Endeavour OS(Arch).  I have tested with the version from the AUR(wowup-cf-bin 2.11.0beta2-1) and the beta2 app image provided here.

OS: EndeavourOS Linux x86_64
Kernel: 6.5.3-arch1-1
Browser: Vivaldi 6.2.3105.48-1

**Comment by Kemmojo** [comment]
Also ppl mentioned similar here: WowUp/WowUp.CF#62

**Comment by tonydero** [comment]
As a note, this doesn't happen for me on the 2.10.0 release appimage version, but as soon as it forces me to update to 2.11.0-beta.2 it starts happening.

Downloading the 2.10.0 release and then editing `wowup_release_channel_2_6` to be `true` in `~/.config/WoWUpCF/preferences.json` allows me to stay on 2.10.0, which works fine.

**Comment by jliddev** [comment]
Have not been able to reproduce this issue on any flavor of linux. Is there any error logged in the log files

~/.config/WowUpCf/logs

**Comment by Zawaken** [comment]
I see these in main.log

Not sure this is much to work off of, I can add full log from startup of program too if necessary
```
[2023-10-09 16:30:48.227] [error] webContents render-process-gone
[2023-10-09 16:30:48.228] [error] { reason: 'crashed', exitCode: 139 }
[2023-10-09 16:30:48.228] [info]  Restarting main window
```

**Comment by Urworstnit3m3r** [comment]
I have a similar issue my gray screen starts out as colored pixels and moving the mouse around the would be elements turns them gray.

I have fixed the issue by going into `~/.config/WoWUpCF/preferences.json` and changing `"use_hardware_acceleration": "true",` to be `false`.

I am on Fedora 39 beta and today mesa and kernel were updated.
mesa: 23.2.1-2
kernel: 6.5.6-300
AMD GPU and CPU

When you run the app via terminal and mouse over the window the terminal spits out these errors:

```
Errors:
link failed but did not provide an info log
[9297:1011/130956.045798:ERROR:shared_context_state.cc(81)] Skia shader compilation error
------------------------
// Vertex SKSL
#extension GL_NV_shader_noperspective_interpolation: require
uniform float4 sk_RTAdjust;in float2 position;in float coverage;in float2 localCoord;noperspective out float2 vlocalCoord_S0;noperspective out float vcoverage_S0;void main() {// Primitive Processor QuadPerEdgeAAGeometryProcessor
float2 position = position.xy;vlocalCoord_S0 = localCoord;vcoverage_S0 = coverage;sk_Position = position.xy01;}
// Fragment SKSL
#extension GL_NV_shader_noperspective_interpolation: require
uniform sampler2D uTextureSampler_0_S0;
noperspective in float2 vlocalCoord_S0;noperspective in float vcoverage_S0;void main() {// Stage 0, QuadPerEdgeAAGeometryProcessor
half4 outputColor_S0 = half4(1);float2 texCoord;texCoord = vlocalCoord_S0;outputColor_S0 = (blend_modulate(sample(uTextureSampler_0_S0, texCoord), half4(1)));float coverage = vcoverage_S0;half4 outputCoverage_S0 = half4(half(coverage));{ // Xfer Processor: Porter Duff
sk_FragColor = outputColor_S0 * outputCoverage_S0;}}
// Vertex GLSL
#version 300 es

#extension GL_NV_shader_noperspective_interpolation : require
precision mediump float;
precision mediump sampler2D;
uniform highp vec4 sk_RTAdjust;
in highp vec2 position;
in highp float coverage;
in highp vec2 localCoord;
noperspective out highp vec2 vlocalCoord_S0;
noperspective out highp float vcoverage_S0;
void main() {
    highp vec2 position = position;
    vlocalCoord_S0 = localCoord;
    vcoverage_S0 = coverage;
    gl_Position = vec4(position, 0.0, 1.0);
    gl_Position = vec4(gl_Position.xy * sk_RTAdjust.xz + gl_Position.ww * sk_RTAdjust.yw, 0.0, gl_Position.w);
}

// Fragment GLSL
#version 300 es

#extension GL_NV_shader_noperspective_interpolation : require
precision mediump float;
precision mediump sampler2D;
out mediump vec4 sk_FragColor;
uniform sampler2D uTextureSampler_0_S0;
noperspective in highp vec2 vlocalCoord_S0;
noperspective in highp float vcoverage_S0;
void main() {
    mediump vec4 outputColor_S0 = vec4(1.0);
    highp vec2 texCoord;
    texCoord = vlocalCoord_S0;
    outputColor_S0 = texture(uTextureSampler_0_S0, texCoord, -0.5);
    highp float coverage = vcoverage_S0;
    mediump vec4 outputCoverage_S0 = vec4(coverage);
    {
        sk_FragColor = outputColor_S0 * outputCoverage_S0;
    }
}
```

![Screenshot from 2023-10-11 13-08-06](https://github.com/WowUp/WowUp.CF/assets/37315608/a377184c-5c4f-40ed-9143-6472f8d007d3)

**Comment by jliddev** [comment]
Can you try re-enabling hardware acceleration and deleting the `~/.config/WowUpCf/GPUCache` folder?

**Comment by Urworstnit3m3r** [comment]
> Can you try re-enabling hardware acceleration and deleting the `~/.config/WowUpCf/GPUCache` folder?

This appears to have fixed my gray screen issue. With hardware acceleration on it no longer produces the bad graphic / gray window for me.

**Comment by jliddev** [comment]
Well thats progess

**Comment by thevinter** [comment]
I still have the issue on Arch Linux, even with hardware acceleration disabled. 

The first time I try to open the app it's fine for a couple of seconds, then it becomes gray and I get the following error:

```
03:08:26.117 › Hardware acceleration disabled
[45585:1103/030826.209744:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[45585:1103/030826.209771:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
03:08:26.295 › App ready: 198ms
libva error: vaGetDriverNames() failed with unknown libva error
03:08:26.467 › process.versions {
  node: '18.16.1',
  acorn: '8.8.2',
  ada: '1.0.4',
  ares: '1.19.1',
  brotli: '1.0.9',
  cldr: '43.0',
  icu: '73.1',
  llhttp: '6.0.11',
  modules: '116',
  napi: '8',
  nghttp2: '1.52.0',
  openssl: '1.1.1',
  simdutf: '3.2.2',
  tz: '2023c',
  undici: '5.21.0',
  unicode: '15.0',
  uv: '1.44.2',
  uvwasi: '0.0.15',
  v8: '11.6.189.20-electron.0',
  zlib: '1.2.13.1-motley',
  electron: '26.2.0',
  chrome: '116.0.5845.179'
}
03:08:26.467 › Loading app URL: 370ms
START_WITH_SYSTEM_PREFERENCE_KEY: undefined
START_MINIMIZED_PREFERENCE_KEY: undefined
03:08:26.917 › Checking for update
03:08:26.917 › autoUpdater checking-for-update
03:08:27.108 › [CreateDirectory] '/home/thevinter/.config/WowUpCf/downloads'
Creating tray
IPC_OW_IS_CMP_REQUIRED failed TypeError: Cannot read properties of undefined (reading 'isCMPRequired')
    at /tmp/.mount_wowup-MzEAYT/resources/app.asar/app/ipc-events.js:104:50
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:89468)
    at WebContents.emit (node:events:513:28)
03:08:27.437 › Update for version 2.11.0-beta.2 is not available (latest version: 2.10.0, downgrade is disallowed).
03:08:27.437 › autoUpdater update-not-available {
  tag: 'v2.10.0',
  version: '2.10.0',
  files: [
    {
      url: 'WowUp-CF-2.10.0.AppImage',
      sha512: 'QgxU6jyMznXemUG8TGyxgHeJLwaKTK+2ERvRaHd/hYEr6TnqahykSZQ852p1ghgLTroLC14l5bpv9uhpiTu6rA==',
      size: 105817179,
      blockMapSize: 111727
    }
  ],
  path: 'WowUp-CF-2.10.0.AppImage',
  sha512: 'QgxU6jyMznXemUG8TGyxgHeJLwaKTK+2ERvRaHd/hYEr6TnqahykSZQ852p1ghgLTroLC14l5bpv9uhpiTu6rA==',
  releaseDate: '2023-07-26T17:09:07.648Z',
  releaseName: '2.10.0',
  releaseNotes: '<h4>Changes</h4>\n' +
    '    <ul>\n' +
    '    <li>Support new TukUI API</li>\n' +
    '    <li>New retry logic when downloading an addon update</li>\n' +
    '    </ul>\n' +
    '    <h4>Fixes</h4>\n' +
    '    <ul>\n' +
    '    <li>Fix XPTR client breaking Retail install</li>\n' +
    '    <li>Fix WTF explorer</li>\n' +
    '    <li>Fix External link handling</li>\n' +
    '    <li>If downloading an update fails button should no longer stay in error state forever</li>\n' +
    '    </ul>'
}
03:08:27.438 › checkForUpdates {
  versionInfo: {
    tag: 'v2.10.0',
    version: '2.10.0',
    files: [ '[object]' ],
    path: 'WowUp-CF-2.10.0.AppImage',
    sha512: 'QgxU6jyMznXemUG8TGyxgHeJLwaKTK+2ERvRaHd/hYEr6TnqahykSZQ852p1ghgLTroLC14l5bpv9uhpiTu6rA==',
    releaseDate: '2023-07-26T17:09:07.648Z',
    releaseName: '2.10.0',
    releaseNotes: '<h4>Changes</h4>\n' +
      '    <ul>\n' +
      '    <li>Support new TukUI API</li>\n' +
      '    <li>New retry logic when downloading an addon update</li>\n' +
      '    </ul>\n' +
      '    <h4>Fixes</h4>\n' +
      '    <ul>\n' +
      '    <li>Fix XPTR client breaking Retail install</li>\n' +
      '    <li>Fix WTF explorer</li>\n' +
      '    <li>Fix External link handling</li>\n' +
      '    <li>If downloading an update fails button should no longer stay in error state forever</li>\n' +
      '    </ul>'
  },
  updateInfo: {
    tag: 'v2.10.0',
    version: '2.10.0',
    files: [ '[object]' ],
    path: 'WowUp-CF-2.10.0.AppImage',
    sha512: 'QgxU6jyMznXemUG8TGyxgHeJLwaKTK+2ERvRaHd/hYEr6TnqahykSZQ852p1ghgLTroLC14l5bpv9uhpiTu6rA==',
    releaseDate: '2023-07-26T17:09:07.648Z',
    releaseName: '2.10.0',
    releaseNotes: '<h4>Changes</h4>\n' +
      '    <ul>\n' +
      '    <li>Support new TukUI API</li>\n' +
      '    <li>New retry logic when downloading an addon update</li>\n' +
      '    </ul>\n' +
      '    <h4>Fixes</h4>\n' +
      '    <ul>\n' +
      '    <li>Fix XPTR client breaking Retail install</li>\n' +
      '    <li>Fix WTF explorer</li>\n' +
      '    <li>Fix External link handling</li>\n' +
      '    <li>If downloading an update fails button should no longer stay in error state forever</li>\n' +
      '    </ul>'
  }
}
03:08:33.632 › webContents render-process-gone
03:08:33.632 › { reason: 'crashed', exitCode: 139 }
03:08:33.633 › Restarting main window
```

If I try opening it again after that I get:

```
03:06:51.593 › Loading app URL: 345ms
libva error: vaGetDriverNames() failed with unknown libva error
03:06:51.657 › Error: ERR_FAILED (-2) loading 'file:///tmp/.mount_wowup-8FeBvC/resources/app.asar/dist/index.html'
    at rejectAndCleanup (node:electron/js2c/browser_init:2:85371)
    at WebContents.stopLoadingListener (node:electron/js2c/browser_init:2:85758)
    at WebContents.emit (node:events:513:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94495)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/tmp/.mount_wowup-MzEAYT/resources/app.asar/app/main.js:257:67)
    at BrowserWindow.emit (node:events:525:35)
```

And the only way to fix it is to use `killall wowup-cf`

Interestingly this happens only with `[wowup-cf-bin](https://aur.archlinux.org/packages/wowup-cf-bin)` from the AUR and not with `[wowup](https://aur.archlinux.org/packages/wowup)` or `[wowup-bin](https://aur.archlinux.org/packages/wowup-bin)`. 

I checked and noticed that only `wowup-cf-bin` was upgraded to `2.11.0beta2`, so I tried downgrading the PKGBUILD to 2.10.0 and it worked, confirming it's indeed an issue from 2.11.0 onwards as mentioned in #62 

However, after doing this I tried deleting my local binary and downloading `2.11.0beta2` from the AUR again the issue seems to have disappeared. The only thing that I did was updating some of my addons so I assume there's a specifc combination of events that produces the crash. I also tried looking at the coredump but it didn't have meaningful info. 

**PS: Comments on the beta release**
To debug it locally I tried cloning and running the repo from branch [feature/2.11.0](https://github.com/WowUp/WowUp/tree/feature/2.11.0) since it's the one with the latest updates. Sadly, it doesn't look maintained at all. 

- It now requires the ow-electron dependency which is not linked in the `package.json`
- A lot of things in `package.json` reference `ow-electron:*` scripts which are not present themselves
- I tried fixing it myself by adding the missing scripts with the following, but it didn't work and it looked like electron wasn't actually serving the application:
```
 "ow-electron:serve-tsc": "tsc -p tsconfig.serve.json",
 "ow-electron:serve": "wait-on tcp:4200 && npm run ow-electron:serve-tsc && npx ow-electron . --serve",
```
- In the end I managed to get the application running locally by building the angular source and then serving it directly with `npx ow-electron main.js`, however this started the non curseforge version for some reason, so I gave up.

**My suggestion would be to downgrade the AUR package (and any other) to a non-beta version and wait until 2.11 is stable to release it as a binary** 
The general expectation for `*-bin` packages in the AUR is that they contain stable releases of the software, and any non-stable release should be either in `*-git` or in `*-beta-bin`

**Comment by scrazzy** [comment]
Still same problem in beta.3 on Ubuntu 22.04 with AppImage. 

05:42:39.019 › webContents render-process-gone
05:42:39.019 › { reason: 'crashed', exitCode: 11 }
05:42:39.019 › Restarting main window
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94495)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/tmp/.mount_WowUp-P7mS7L/resources/app.asar/app/main.js:258:67)
    at BrowserWindow.emit (node:events:525:35)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94495)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/tmp/.mount_WowUp-P7mS7L/resources/app.asar/app/main.js:255:67)
    at BrowserWindow.emit (node:events:525:35)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94495)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/tmp/.mount_WowUp-P7mS7L/resources/app.asar/app/main.js:381:114)
    at BrowserWindow.emit (node:events:513:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94495)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/tmp/.mount_WowUp-P7mS7L/resources/app.asar/app/main.js:385:114)
    at BrowserWindow.emit (node:events:525:35)
05:42:48.912 › window config saved
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94495)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/tmp/.mount_WowUp-P7mS7L/resources/app.asar/app/main.js:377:114)
    at BrowserWindow.emit (node:events:525:35)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94495)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/tmp/.mount_WowUp-P7mS7L/resources/app.asar/app/main.js:258:67)
    at BrowserWindow.emit (node:events:525:35)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94495)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/tmp/.mount_WowUp-P7mS7L/resources/app.asar/app/main.js:255:67)
    at BrowserWindow.emit (node:events:525:35)

**Comment by IncrediblePony** [comment]
Can confirm same behaviour on `WowUp-curseforge-2.11.0-beta.6`

```bash
ﬀ ./WowUp-CF-2.11.0-beta.6.AppImage 
20:32:45.916 › Main starting
20:32:45.918 › Electron: 26.2.0
20:32:45.919 › BinaryPath: /tmp/.mount_WowUp-bzf5Eg/wowup-cf
20:32:45.919 › ExecPath /tmp/.mount_WowUp-bzf5Eg/wowup-cf
20:32:45.919 › Args [ '/tmp/.mount_WowUp-bzf5Eg/wowup-cf' ]
20:32:45.919 › Log path: /home/mads/.config/WowUpCf/logs
20:32:45.920 › ARGV { _: [], serve: false, hidden: false }
20:32:45.920 › USER_AGENT WowUp-Client/2.11.0-beta.6 (Linux; 6.5.6-76060506-generic; x64; CF;  +https://wowup.io)
20:32:45.930 › Hardware acceleration enabled
20:32:46.229 › App ready: 309ms
20:32:46.280 › process.versions {
  node: '18.16.1',
  acorn: '8.8.2',
  ada: '1.0.4',
  ares: '1.19.1',
  brotli: '1.0.9',
  cldr: '43.0',
  icu: '73.1',
  llhttp: '6.0.11',
  modules: '116',
  napi: '8',
  nghttp2: '1.52.0',
  openssl: '1.1.1',
  simdutf: '3.2.2',
  tz: '2023c',
  undici: '5.21.0',
  unicode: '15.0',
  uv: '1.44.2',
  uvwasi: '0.0.15',
  v8: '11.6.189.20-electron.0',
  zlib: '1.2.13.1-motley',
  electron: '26.2.0',
  chrome: '116.0.5845.179'
}
20:32:46.281 › Loading app URL: 361ms
20:32:46.322 › Error: ERR_FAILED (-2) loading 'file:///tmp/.mount_WowUp-bzf5Eg/resources/app.asar/dist/index.html'
    at rejectAndCleanup (node:electron/js2c/browser_init:2:85371)
    at WebContents.stopLoadingListener (node:electron/js2c/browser_init:2:85758)
    at WebContents.emit (node:events:513:28)
```

**Comment by AirflashX** [comment]
I have the same problem with the release of 2.11.0 appimage.
The error wasn't there in 2.10.0

https://pastebin.com/QCjFbCWw

**Comment by Edu4rdSHL** [comment]
I wonder why this “latest stable” release was made without even checking this issue which affects all the Linux users.

I'll personally hold https://aur.archlinux.org/packages/wowup-cf-bin on 2.10 until it gets fixed.

**Comment by tonydero** [comment]
> I wonder why this “latest stable” release was made without even checking this issue which affects all the Linux users.
> 
> I'll personally hold https://aur.archlinux.org/packages/wowup-cf-bin on 2.10 until it gets fixed.

Is there a setting/config value to change somewhere to keep it on 2.10? As far as I can tell you can only keep it on a specific channel, so it still forces the update to 2.11, or am I missing something?

> Maybe you should do something about it.

Is this really the attitude of the devs here? "Fix it yourself or shut up" seems pretty immature. I get that maybe you aren't big on Linux and/or just really couldn't replicate it for whatever reason, but that just seems like an inappropriate response to someone attempting to provide a temporary bandaid to keep it working for those of us using that package.

**Comment by tonydero** [comment]
> I wonder why this “latest stable” release was made without even checking this issue which affects all the Linux users.
> 
> I'll personally hold https://aur.archlinux.org/packages/wowup-cf-bin on 2.10 until it gets fixed.

This doesn't seem to work for me. Is there a setting/config value to change to keep it on a specific version that I missed? As opposed to just a specific channel? It is still forcing an update to 2.11 for me.

**Comment by tonydero** [comment]
> What "doesn't seems to work"? If you have the AUR package installed, you can just click on "update" and nothing will happens because the app doesn't have permissions to write on the directory it was installed.

Ah! Didn't realize the update popup would go away if I clicked it a few more times.

**Comment by evensis** [comment]
Thanks for the workaround - works nicely. One can only assume Linux support has been dropped given no replies by the developer on this issue in over 3 months, and subsequently putting it into production with the multi-reported show stopper in tow.

**Comment by jliddev** [comment]
Interesting assumption.

![image](https://github.com/WowUp/WowUp.CF/assets/20467484/11bbe546-a409-4578-a027-d6d7ad68cd28)

**Comment by evensis** [comment]
@jliddev - lovely stuff, very pleased to see my assumption quashed! Although admittedly I can get it to do the same thing after wiping out the folder you've got up and it will stay there fine, that is, until you try moving the mouse inside the viewport lol. Look forward to release! :)

**Comment by Edu4rdSHL** [comment]
Latest beta fixed the issue for me.

**Comment by Jemikwa** [comment]
Same! The 2.11.1 beta runs great, no UI disappearing issues any more. Thanks for the quick fix!

**Comment by Edu4rdSHL** [comment]
Hi, @jliddev, are there any chances that you make a 2.11.1 stable release for this fix? Thanks in advance.

**Comment by Edu4rdSHL** [comment]
Hi, @jliddev, can you please make a minor stable release now that it's fixed? Thanks.

**Comment by thevinter** [comment]
Any updates on this? For me it still occurrs on 2.12.0

**Comment by jliddev** [comment]
Give this a try, app image is working on my fedora 40 https://github.com/WowUp/WowUp/issues/1474#issuecomment-2101247030
